version: "3.9"

services: 
    app:
        build: .
        volumes: 
            - ./:/app
        environment: 
            - DB_HOST=db
            - DB_NAME=book_review
            - PORT=3000
        ports: 
            - "3000:3000"
        restart: unless-stopped
        depends_on: 
            - database
    
    database:
        image: mongo
        volumes: 
            - ./docker/data/db:/data/db
        restart: unless-stopped
        