version: "3.9"

#NETWORD
networks: 
    review-book-network:
        driver: bridge

services: 
    db:
        container_name: mongo-container
        image: mongo:4.4.6
        networks: 
            - review-book-network
        volumes: 
            - ./docker/mongo/:/data/db/
        ports: 
            - "27018:27017"
            
    app:
        container_name: app-container
        image: node-app-image
        networks: 
            - review-book-network
        volumes: 
            - .:/usr/src/app
        ports: 
            - 3000:3000
        environment: 
            - DB_NAME=book_review
            - DB_PORT=27017
            - DB_HOST=db
            - ACCESS_TIMEOUT=3000
            - PORT=3000
        depends_on: 
            - db
            
        